### ISSUE TITLE
can't run it

### ISSUE THREAD

**Issue by Yehuda-V** [GoodBoyNinja/cep-symlink#1]
Hello,

The following message appears whenever I run it in the terminal in Visual Studio Code (which runs as admin):
`You need to run this script as administrator.If you are using VSCode please relaunch it as administrator.If you are using the command - prompt please relaunch it as administrator.
`
Any idea how to fix it?

**Comment by GoodBoyNinja** [comment]
On windows it's always a good idea to turn on Dev Mode for symlink to work flawlessly
https://pureinfotech.com/enable-developer-mode-windows-11/
